Repository feelSpring/spring, pull requests merged in 2024-08, with the labels that each got.

#67 [feat] 회원가입 페이지 추가
  public/stylesheets/users/user.css
  routes/user/index.js
  views/header.ejs
  views/user/changePassword.ejs
  views/user/doctorJoin.ejs
  views/user/emailVerification.ejs
  views/user/login.ejs
  views/user/patientJoin.ejs
Labels: :kiwi_fruit: feature

#69 [database] 환자, 의사, 요청상태, 환자관리 테이블 추가
  models/doctor.js
  models/index.js
  models/password_token.js
  models/patient_management.js
  models/request_status.js
  models/user.js
Labels: 📀 database

#74 [feat] 마이페이지 뷰 작성
  package-lock.json
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-Medium.ttf
  public/images/right.png
  public/stylesheets/mypage.css
  public/stylesheets/sleep.css
  public/stylesheets/test.css
  routes/mypage/index.js
  views/mypage/mypage.ejs
  views/sleep/sleep.ejs
Labels: :kiwi_fruit: feature

#76 [REFACTOR] 약 페이지 css 수정
  public/stylesheets/prescription.css
Labels: 💻 refactor

#78 [feat] 마이 페이지 백엔드 기능
  authenticateToken.js
  controllers/mypage/agreementGET.js
  controllers/mypage/agreementPUT.js
  controllers/mypage/managementGET.js
  controllers/mypage/managementPUT.js
  models/myPageQuery.js
  models/request_status.js
  public/stylesheets/mypage.css
  routes/index.js
  routes/mypage/index.js
  views/mypage/mypage.ejs
Labels: :kiwi_fruit: feature

#82 [feat] 환자와 의사 회원가입, 로그인 기능 추가
  controllers/user/emailCheckingPOST.js
  controllers/user/joinDoctorPOST.js
  controllers/user/joinPatientPOST.js
  controllers/user/loginPOST.js
  routes/user/index.js
  uploads/certification-1723561847400-421066323.png
  views/user/doctorJoin.ejs
  views/user/login.ejs
  views/user/patientJoin.ejs
Labels: :kiwi_fruit: feature, 💻 refactor

#84 [feat] 환자 추가 페이지
  controllers/doctor/addPatientPOST.js
  controllers/doctor/searchPatientPOST.js
  models/addPatientQuery.js
  public/stylesheets/doctor_addPatient.css
  routes/doctor/index.js
  routes/index.js
  views/doctor/popupAddPatient.ejs
Labels: :kiwi_fruit: feature

#86 [feat] 환자페이지 열람, 요청목록 확인
  .idea/dataSources.xml
  controllers/doctor_main/cancelRequestPOST.js
  controllers/doctor_main/openPatientPageGET.js
  controllers/doctor_main/requestListGET.js
  controllers/doctor_main/searchMyPatientsPOST.js
  models/doctorMainQuery.js
  public/javascripts/myPatients.js
  public/stylesheets/doctor_main.css
  routes/doctor_main/index.js
  routes/index.js
  views/doctor_main/doctor_main.ejs
  views/doctor_main/patientAddButton.ejs
  views/doctor_main/patientPageViewButton.ejs
  views/doctor_main/patientSearch.ejs
  views/doctor_main/patientSearchList.ejs
  views/doctor_main/requestCancelButton.ejs
  views/doctor_main/requestList.ejs
Labels: :kiwi_fruit: feature

#89 [feat] 의사 비밀번호 변경기능 추가
  controllers/user/passwordPUT.js
  controllers/user/passwordResetLinkPOST.js
  views/user/emailVerification.ejs
Labels: :kiwi_fruit: feature

#88 [feat] 보드 작업 중
  controllers/board/boardUserInfoGET.js
  controllers/prescription/mainChartGET.js
  models/boardQuery.js
  models/myPageQuery.js
  public/stylesheets/board.css
  routes/board/index.js
  routes/index.js
  routes/prescription/index.js
  views/board/board.ejs
Labels: :kiwi_fruit: feature

#91 [refactor] 의사 메인페이지 수정
  controllers/doctor_main/getAllPatientsGET.js
  models/doctorMainQuery.js
  public/javascripts/myPatients.js
  routes/doctor_main/index.js
  views/doctor_main/doctor_main.ejs
Labels: 💻 refactor

#92 [refactor] 의사 페이지 전반적 수정
  authenticateToken.js
  controllers/doctor/addPatientPOST.js
  controllers/doctor/searchPatientPOST.js
  controllers/doctor_main/cancelRequestPOST.js
  controllers/doctor_main/requestListGET.js
  controllers/doctor_main/searchMyPatientsPOST.js
  controllers/user/passwordPUT.js
  models/doctorMainQuery.js
  public/javascripts/myPatients.js
  public/stylesheets/doctor_addPatient.css
  public/stylesheets/doctor_main.css
  routes/doctor_main/index.js
  uploads/certification-1723698197419-797421853.png
  views/doctor/popupAddPatient.ejs
  views/doctor_main/doctor_main.ejs
  views/doctor_main/patientAddButton.ejs
  views/doctor_main/patientSearch.ejs
  views/doctor_main/requestCancelButton.ejs
  views/doctor_main/requestList.ejs
  views/user/login.ejs
Labels: 🛠 fix, 💻 refactor

#95 [refactor] 의사페이지 기능 수정
  controllers/doctor_main/getAllPatientsGET.js
  routes/doctor_main/index.js
  views/doctor_main/doctor_main.ejs
Labels: 🛠 fix

#97 [refactor] 코드 수정
  controllers/mypage/agreementGET.js
  controllers/mypage/agreementPUT.js
  controllers/mypage/managementGET.js
  controllers/mypage/managementPUT.js
  models/myPageQuery.js
Labels: 🛠 fix
