Repository feelSpring/spring, pull requests merged in 2024-06, with the labels that each got.

#12 [feat] 다이어리 html, css 작성
  app.js
  controllers/diaryController.js
  models/diaryModel.js
  models/diaryphotoModel.js
  package-lock.json
  package.json
  public/stylesheets/diary.css
  routes/diary/index.js
  routes/index.js
  views/diary.ejs
  views/diary/diary.ejs
Labels: :kiwi_fruit: feature

#5 [feat] 회원 뷰 기능 추가
  controllers/userController.js
  public/images/spring_user_logo.png
  public/images/user_background.png
  public/stylesheets/users/user.css
  routes/users.js
  views/header.ejs
  views/users/changePassword.ejs
  views/users/emailVerification.ejs
  views/users/join.ejs
  views/users/login.ejs
Labels: :kiwi_fruit: feature

#15 🗄️ 시퀄라이즈 config.js 파일 추가
  config/config.js
Labels: 📀 database

#18 [FEAT] 약 html, css 코드 추가
  public/stylesheets/prescription.css
  views/prescription/prescription.ejs
  views/prescription/prescriptionCalendar.ejs
  views/prescription/prescriptionChart.ejs
  views/prescription/prescriptionContent.ejs
  views/prescription/prescriptionRecord.ejs
Labels: :kiwi_fruit: feature

#20 [feat] 수면 기록 html, css 작성
  routes/sleep/index.js
  views/sleep.ejs
Labels: :kiwi_fruit: feature

#24 [refactor] sleep 경로 수정
  routes/index.js
  routes/sleep/index.js
  views/sleep/sleep.ejs
Labels: 💻 refactor

#28 [feat] 로그인, 로그아웃, 회원가입 기능
  app.js
  authenticateToken.js
  controllers/user/emailCheckingPOST.js
  controllers/user/joinPOST.js
  controllers/user/loginPOST.js
  controllers/userController.js
  models/user.js
  public/stylesheets/header.css
  routes/user/index.js
  routes/users.js
  views/header.ejs
  views/user/changePassword.ejs
  views/user/emailVerification.ejs
  views/user/join.ejs
  views/user/login.ejs
  views/users/join.ejs
  views/users/login.ejs
Labels: :kiwi_fruit: feature

#27 [feat] 다이어리 기능 추가
  .gitignore
  app.js
  controllers/diary/diaryGET.js
  controllers/diary/diaryPOST.js
  controllers/diaryController.js
  models/diary.js
  models/diaryModel.js
  models/diaryQuery.js
  models/diaryphotoModel.js
  models/index.js
  package-lock.json
  package.json
  public/stylesheets/diary.css
  routes/diary/index.js
  views/diary.ejs
  views/diary/diary.ejs
Labels: :kiwi_fruit: feature

#33 [feat] 토큰 복호화
  authenticateToken.js
  controllers/test/testPOST.js
  controllers/user/loginPOST.js
  package-lock.json
  views/test/test.ejs
  views/test/testContent.ejs
Labels: :kiwi_fruit: feature

#35 [feat] 약 백앤드 기능 추가
  app.js
  controllers/prescription/chartGET.js
  controllers/prescription/prescriptionContentGET.js
  controllers/prescription/prescriptionContentPOST.js
  controllers/prescription/prescriptionReportGET.js
  controllers/prescription/prescriptionReportPOST.js
  models/index.js
  models/prescription.js
  models/prescriptionQuery.js
  models/prescription_report.js
  package.json
  public/stylesheets/menu.css
  public/stylesheets/prescription.css
  routes/index.js
  routes/prescription/index.js
  views/menu.ejs
  views/prescription/prescription.ejs
  views/prescription/prescriptionChart.ejs
  views/prescription/prescriptionContent.ejs
  views/prescription/prescriptionRecord.ejs
  views/prescription/prescriptionReport.ejs
Labels: :kiwi_fruit: feature

#37 [feat] 수면기록 백엔드 기능 추가
  .gitignore
  app.js
  controllers/sleep/getLast7DaysSleep.js
  controllers/sleep/getTotalSleep.js
  controllers/sleep/sleepByDateGET.js
  controllers/sleep/sleepGET.js
  controllers/sleep/sleepPOST.js
  models/index.js
  models/sleepQuery.js
  models/sleep_report.js
  package-lock.json
  package.json
  public/stylesheets/sleep.css
  routes/index.js
  routes/sleep/index.js
  views/sleep/sleep.ejs
Labels: :kiwi_fruit: feature

#39 [feat] 다이어리 기능 토큰 적용
  controllers/diary/diaryGET.js
  controllers/diary/diaryPOST.js
  models/diaryQuery.js
  views/diary/diary.ejs
Labels: 🛠 fix, :kiwi_fruit: feature

#41 [feat] 수면기록 기능 토큰 적용
  controllers/sleep/getLast7DaysSleep.js
  controllers/sleep/getTotalSleep.js
  controllers/sleep/sleepByDateGET.js
  controllers/sleep/sleepPOST.js
  models/sleepQuery.js
  public/stylesheets/menu.css
  views/menu.ejs
  views/sleep/sleep.ejs
Labels: :kiwi_fruit: feature

#47 [refactor] 약 css 수정
  public/stylesheets/prescription.css
  views/prescription/prescriptionChart.ejs
  views/prescription/prescriptionContent.ejs
  views/prescription/prescriptionReport.ejs
Labels: 💻 refactor

#49 [refactor] 약 css 재수정
  public/stylesheets/prescription.css
Labels: 💻 refactor

#51 [feat] 토큰 기반 인가 코드 추가
  app.js
  controllers/prescription/chartGET.js
  controllers/prescription/prescriptionContentDELETE.js
  controllers/prescription/prescriptionContentEDIT.js
  controllers/prescription/prescriptionContentGET.js
  controllers/prescription/prescriptionContentPOST.js
  controllers/prescription/prescriptionReportDELETE.js
  controllers/prescription/prescriptionReportEDIT.js
  controllers/prescription/prescriptionReportGET.js
  controllers/prescription/prescriptionReportPOST.js
  models/prescriptionQuery.js
  routes/prescription/index.js
  views/prescription/prescription.ejs
  views/prescription/prescriptionContent.ejs
  views/prescription/prescriptionReport.ejs
Labels: :kiwi_fruit: feature

#52 [feat] 비밀번호 변경 기능
  controllers/user/passwordPUT.js
  controllers/user/passwordResetLinkPOST.js
  emailVerificationConfig.js
  models/index.js
  models/password_token.js
  package.json
  routes/index.js
  routes/user/index.js
  views/index.ejs
  views/user/changePassword.ejs
  views/user/emailVerification.ejs
  views/user/join.ejs
  views/user/login.ejs
Labels: :kiwi_fruit: feature, 💻 refactor, 📀 database

#54 [refactor] 기본 페이지, 메뉴 css 변경
  views/index.ejs
  views/menu.ejs
Labels: 💻 refactor

#56 [bug] 회원가입 버그 수정
  controllers/user/emailCheckingPOST.js
  controllers/user/joinPOST.js
  controllers/user/loginPOST.js
  controllers/user/passwordPUT.js
  controllers/user/passwordResetLinkPOST.js
  views/header.ejs
  views/user/changePassword.ejs
  views/user/emailVerification.ejs
  views/user/join.ejs
  views/user/login.ejs
Labels: 🚨 bug
